### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by sheesh**
Hi all. This is a first stab at a README.md. Feel free to make changes or let me know if you have any feedback. Thanks!

### CODE REVIEW

**Comment by boonebgorges** [comment]
I made a few changes, and added a Technical Overview section.

Thanks for the PR!

**Comment by sheesh** [comment]
Thank you, Boone! Looks great!

On Thursday, October 15, 2015, Boone Gorges notifications@github.com
wrote:

> I made a few changes, and added a Technical Overview section.
> 
> Thanks for the PR!
> 
> On 10/15/2015 09:28 AM, sheesh wrote:
> 
> > Hi all. This is a first stab at a README.md. Feel free to make changes
> > or let me know if you have any feedback. Thanks!
> > 
> > ---
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/cuny-academic-commons/social-paper/pull/25
> > 
> > Commit Summary
> > - Create README.md
> > 
> > File Changes
> > - _A_ README.md
> >   <
> >   https://github.com/cuny-academic-commons/social-paper/pull/25/files#diff-0
> > 
> > (20)
> > 
> > Patch Links:
> > - https://github.com/cuny-academic-commons/social-paper/pull/25.patch
> > - https://github.com/cuny-academic-commons/social-paper/pull/25.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cuny-academic-commons/social-paper/pull/25.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cuny-academic-commons/social-paper/pull/25#issuecomment-148510181
> .

##

**Comment by christianwach** [comment]
Is it still true about WP Side Comments? I haven't tested that for a long time and all the current JS rather assumes Inline Comments.

**Comment by r-a-y** [comment]
> Is it still true about WP Side Comments?

I would say no.

Since we started working on Inline Comments integration, we can probably remove the conditional code and make Inline Comments the only commenting plugin we support.

**Comment by boonebgorges** [comment]
Thanks, all. I've removed mention of WP Side Comments from the readme.

**Comment by r-a-y** [comment]
I've removed references to WP Side Comments from our codebase in commit a2377f8.

**Pull request merged**
